### ISSUE TITLE
Deploying to Dokku without exposing to external network

### ISSUE THREAD

**Issue by thomasfedb** [beydogan/dokku-vendor#1]
Thanks for creating this handy app. Would you consider adding instructions in the `README` as to how you can deploy this with Dokku without opening up your cache to the whole world? I tried to figure this out from the Dokku docs, but it was far from obvious.

**Comment by beydogan** [comment]
I'm glad app is helpful to you. I think it can be done with custom nginx configuration by restricting IPs. I will add instructions to `README`.

**Comment by thomasfedb** [comment]
Thanks @beydogan, that's an approach I hadn't considered. Cheers.
