### ISSUE TITLE
How to create .buildpacks file for rails/webpack

### ISSUE THREAD

**Issue by sergio-rivas** [beydogan/dokku-vendor#3]
rails w/ webpack requires the use of two buildpacks: nodejs & ruby. 

I have tried creating the following .buildpacks list, but it doesn't seem to work:
```
http://IP_ADDRESS:PORT/heroku-buildpack-nodejs/
http://IP_ADDRESS:PORT/heroku-buildpack-ruby/
```
it works perfect when running non-webpack projects that have BUILDPACK_URL as `http://IP_ADDRESS:PORT/heroku-buildpack-ruby/`

I think when using .buildpacks, it perhaps needs a more specific url to the specific tar? Is there anywhere I can find the full url to nodejs buildpacks?

**Comment by beydogan** [comment]
Hi @sergio-rivas, `.buildpacks` file should be like this for example;

```
https://github.com/heroku/heroku-buildpack-nodejs.git
https://github.com/heroku/heroku-buildpack-ruby.git
```

dokku-vendor doesn't provide buildpack, it only provides assets for buildpack-ruby, like ruby source code etc. And dokku-vendor only works for buildpack-ruby so you can still use it as its mentioned in the readme.

**Comment by beydogan** [comment]
Have you fixed the issue @sergio-rivas ? I'm closing this for now.
